### ISSUE TITLE
[iOS] Allow disabling of tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1083]
- [x]  Crashlytics is staying
- [x] If Agreed without sharing usage data or disabled in settings, then screen tracking and all other tracking can be disabled.
- [x] For existing users
- [x]   Toggle in settings should be ON after the update
- [x]   The tracking should be enabled
- [x] Note: app restart is not required to disable/enable analytics.
- [x] Link in settings leads to privacy policy page:  https://gnosis-safe.io/privacy/
- [x] Firebase docs: https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios 

Zeplin: 

- https://zpl.io/annMenk
- https://zpl.io/amPqWPe

**Comment by elgatovital** [comment]
please add link to the privacy policy

**Comment by liliya-soroka** [comment]
@sche , what version will contain it ?
I have tried the latest 2.14.0 and 2.13.0 and could not find it

**Comment by liliya-soroka** [comment]
Verified
app version 2.15.0 (406)
