### ISSUE TITLE
[iOS] Add missing tracking

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1634]
- [x] `num_keys_ledger_nano_x` user property should be set with every app start
- [x] `screen_collectibles_not_supported` should be tracked
- [x] `user_collectibles_open_in_web` user event should be tracked together with chain_id parameter
- [x] `user_try_demo` should be tracked
- [x] `screen_settings_app_appearance` should be tracked
- [x] `screen_settings_app_chain_prefix` should be tracked
- [x] `user_settings_open_terms` should be tracked (From App Settings) 
- [x] `user_settings_open_privacy_policy` should be tracked (From App Settings) 
- [x] `user_settings_open_licenses` should be tracked
- [x] `user_settings_rate_app should` be tracked
- [ ] `user_banner_passcode_skip` should be tracked
- [ ] `user_banner_passcode_create` should be tracked

**Comment by liliya-soroka** [comment]
the task will be tested after release 3.4.0 , before 3.5.0 release

**Comment by liliya-soroka** [comment]
Missed tracking:
I think that the tracking was missed after moving all options to the "About Gnosis safe" Should we also add tracking for "about..." screen ?
- [x]  user_settings_open_terms should be tracked (From App Settings)
- [x]  user_settings_open_privacy_policy should be tracked (From App Settings)
- [x]  user_settings_open_licenses should be tracked
- [x]  user_settings_rate_app should be tracked

Can not be tested because passcode banner functionality was missed 

- [ ]  user_banner_passcode_skip should be tracked
- [ ]  user_banner_passcode_create should be tracked
https://app.zenhub.com/workspaces/mobile-development-board-60cc78740f488d000e996335/issues/gnosis/safe-ios/1703
app version 3.5.0 branch

**Comment by sche** [comment]
> Can not be tested because passcode banner functionality was missed

As we show the explicit "Setup passcode" screen when adding safe, this banner is not displayed for new users. We also offer to set up passcode when adding signing keys.

We need to create a maintenance issue to remove this banner.

**Comment by liliya-soroka** [comment]
Verified
app version 3.5.0 (748)
