### ISSUE TITLE
[ExecuteTx] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1639]
- [x] Review screen shown
screen_exec_tx_review

- [x] Edit transaction fee opened
screen_edit_exec_tx_fee

- [x] Fee field edited (with parameter = to the name of the field)
user_edit_exec_tx_fee_ fields: 
fields: comma-separated [nonce, gasLimit, maxFee, maxPriorityFee, gasPrice]

- [x] Advanced parameters opened
screen_exec_tx_review_advanced

- [x] Select key opened
screen_select_exec_key

- [x] Select key changed
user_select_exec_key_change

- [x] Transaction submitted success screen (params: type of key, type of transaction)
screen_exec_tx_submitted
keyType: one of [imported, generated, wallet_connect, ledger_nano_x]
chainId: String

- [x] Ledger guiding screen(s)
screen_exec_tx_ledger_confirm

- [x] WalletConnect transaction sent
No need for now. Will be covered with the key parameter when executed.

- [x] Transaction submission failed - Log non-fatal? (potentially many errors)
 Let’s not use errors details yet. Can be added later.
user_exec_tx_failed
chainId: Chain id

- [ ] Opened details of the pending transaction
Extending of existing tracking event: screen_transactions_details
status: one of [AWAITING_CONFIRMATIONS, AWAITING_YOUR_CONFIRMATION, AWAITING_EXECUTION, CANCELLED, FAILED, SUCCESS, PENDING]

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0
