### ISSUE TITLE
[TransferAssets] Funds transfer tracking

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1654]
Implement tracking for Funds transfer.

- [x] user_select_receive_asset
- [x] user_select_send_asset
- [x] screen_select_asset
- [ ] screen_add_owner_to_send_assets
- [x] user_select_add_owner_to_send_assets
- [x] screen_asset_tranfer
- [x] screen_review_asset_transfer
- [x] screen_asset_transfer_advanced_params
- [x] screen_asset_transfer_success

- [x] Update [tracking document](https://docs.google.com/spreadsheets/d/1mj9iQIhpM-Pak7lQMb1dmxhQn1QdJoJyhbc730dZNzA/edit#gid=0) with added tracking events

**Comment by DmitryBespalov** [comment]
@sche please adjust the duplicate screen/button events

**Comment by liliya-soroka** [comment]
Not implemented:
It will be reported separately 
- [ ] screen_add_owner_to_send_assets
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ca2a431e-98ea-4c2e-8d11-bfd7fac1fd9d)
