### ISSUE TITLE
[Intercom] Adjust App Settings

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1655]
- [x] Add icons and sections
- [x] Renaming "Get In Touch" to "Help Center"
- [x] "Chat with us" opens Intercom in a popover screen

**TODO**
Add links to screenshots

**Comment by elgatovital** [comment]
Get In Touch -> Get Support according to screens in figma
Itercom wiring can be done after https://github.com/gnosis/safe-ios/pull/1660 is merged

**Comment by liliya-soroka** [comment]
Nothing happens on Chat with us click

app version 3.5.0 (732) and 3.4.0 (743)

iPhone 11/14.8

**Comment by liliya-soroka** [comment]
Verified
app version 3.5.0 (741)
