### ISSUE TITLE
[ExecuteTx] Execute Transaction v2

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1801]
### Review screen
- [ ] Separators between rows in 'execute options' are too thin - should be 2pt height
- [ ] Fiat amount in header and in fee estimation is not displayed
- [ ] Gas price estimation is not using client gateway's chain config with gas price config
- [ ] Error handling needs to be reviewed, documented, and checked for user-facing messages
- [ ] Support wallet connect properly with signing transactions
- [ ] Support ledger nano x signing transactions

### Edit Fee form
- [ ] Add 'reset to defaults' in the form to edit fee parameters

### Advanced parameters
- [ ] Show the eth transaction fields
