### ISSUE TITLE
Address Book on Mobile v2

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2223]
# Problem
gnosis/safe#457 

# Why is it about?
- [ ] Merge Safe names with Address Book
- [ ] Merge Key names with Address Book
- [ ] Tap on an address to add it to Address Book

# Links
[Requirements](https://docs.google.com/document/d/1-lmeMBBjy7vHGpTsve8Tt5tW3MIgZ2ny-C-H8Z3uMQM/edit#)
