### ISSUE TITLE
[MiniRebrand] MiniRebrand (logo, texts)

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2569]
- [x] Launch screen logo
- [ ] App Store
  - [ ] icon
  - [ ] product name
  - [ ] screenshots
  - [ ] description
  - [ ] what's new
- [x] What's new screen
- [x] Gnosis Safe logo → Safe logo
- [x] "Gnosis" texts → "Safe" or us (company)
- [x] App icon
- [x] App name

URLs, Intercom, and emails stay the same.

**Comment by TanyaEfremova** [comment]
Due to the discussion[ in this thread](https://5afe.slack.com/archives/C03CT23SU1Z/p1661345009270079), we will need to change the launcher icons temporarily.

Please, see [here](https://www.figma.com/file/KURqzoDm8b9VNxsWley7gZ/iOS-UI-Kit-%E2%80%94-Rebrand?node-id=1846%3A15989) - we will use the B&W version for the production version.

No new icons are necessary, just a replacement for now.

**Comment by liliya-soroka** [comment]
Verified
App Store changes will be verified after release

app version 3.16.0 (1340)
