### ISSUE TITLE
[KeySec1] Use key for signing & export keys

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2821]
# Description

**Tasks**

- [ ]  Signing
    - [ ]  Use app passcode to unlock sensitive KEK and decrypt the sensitive key
    - [ ]  Then retrieve encrypted owner key and decrypt it with sensitive key
    - [ ]  Update: Confirm tx
    - [ ]  Update: Execute tx
    - [ ]  Update: Create & Submit tx
- [ ]  Export
    - [ ]  Update: Retrieve seed phrase

[Technical steps to do]
1. 
2. 
3. 

# Acceptance Criteria

* [Testable and user-facing criteria]
* 
* 

# Resources

* Links
* 
*
