### ISSUE TITLE
Epic Relay V1 Educational Part

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#2934]
Note: This epic is not mobile/iOS only but includes also web UI and intends to cover the whole UX/UI part of the educational content for relaying V1

As user 
I want to be properly educated what relaying and what my benefits are 
to be able to make an educated decision to use it

**What needs to be done**
Implement the user stories about the educational content

**Acceptance criteria**
User stories implemented

**Stories to be implemented**
Mobile
- [x] https://github.com/safe-global/safe-ios/issues/2930
- [x] https://github.com/safe-global/safe-ios/issues/2931

Web
- [x] https://github.com/safe-global/web-core/issues/1701
- [x] https://github.com/safe-global/web-core/issues/1704

**Comment by the-real-chrizzo** [comment]
Since epics can not properly tracked on a "higher level" between mobile and web, we decided to keep track of the epics in notion
