### ISSUE TITLE
Displaying different notification types and opening the details in the app

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#434]
- [x] User should be asked to enable push notifications after successfully adding their first Safe
- [x] Create new 'remote notification' app extension that will process the push payload and display the localized notification message.
- [x] Parse the notification payload
- [ ] ~Implement checking safe name and checking that safe exists before displaying the notification~
  - Not feasible at the moment: all notifications will be shown, but when clicked, if safe was removed then it might just have no effect (nothing happens)
- [x] Implement formatting the ETH amount for displaying the notification
- [x] Implement switching to the safe and then  opening the transaction details or transaction list

![NotificationsDiagram.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/3d644af5-28b6-49e3-8879-11826f57024a)

# Known issues
- The safe name will not be shown, instead, the abbreviated safe address will be shown
- It is possible that device will receive notifications even if the safe is removed, albeit it should be a rare case

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0(12)
