### ISSUE TITLE
[iOS] Rewrite the remaining SwiftUI screens in UIKit

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#980]
Currently, the remaining of the SwiftUI makes it hard to adapt the Dark Mode and have a consistent code base.

The expected outcome is that the rewritten screens are as designed in UI and integrated in the app.

This issue is about rewriting the remaining screens using UIKit.

These are the screens that remain:
- [ ] Advanced transaction details
- [ ] Get In Touch screen
- [ ] Safe Info Popup
- [ ] Advanced app settings
- [ ] Terms & Conditions (Launch) screen
- [ ] ENS loader view
